### ISSUE TITLE
TO MADBUDA !!!!

### ISSUE THREAD

**Issue by CryptoXman79** [madbuda/hush-1.0.13-bitcoreTLS#1]

**Comment by madbuda** [comment]
Empty issue

**Comment by CryptoXman79** [comment]
so...what is your answer ...are you stealing coins ??

**Comment by CryptoXman79** [comment]
Or is that a 'bug' of your wallet? In that case, you should refund people with no pain.

**Comment by madbuda** [comment]
I'm sorry, I don't know what you're talking about. If you are having an issue feel free to ask for help.

**Comment by madbuda** [comment]
Well damn, when I clicked on this I didn't see the original comment. I do not hold the private keys to this address. An old member of the team does. If you'd provide me with an address I'll reach out and ask him to send you your coins.

Please send me a screenshot of you wallet showing the transaction as proof

**Comment by CryptoXman79** [comment]
![capture 1](https://user-images.githubusercontent.com/35213885/34839810-38f3f298-f703-11e7-863a-2ed64bbcd3bd.JPG)

**Comment by CryptoXman79** [comment]
[~$Copie de Withdraw_History.xlsx](https://github.com/madbuda/hush-1.0.13-bitcoreTLS/files/1623671/Copie.de.Withdraw_History.xlsx)

**Comment by CryptoXman79** [comment]
![capture2](https://user-images.githubusercontent.com/35213885/34840052-18839a58-f704-11e7-89e8-c66cbbcf10d5.JPG)

**Comment by CryptoXman79** [comment]
This is my withdraw from cryptopia ....to the famous watchonly address....

**Comment by madbuda** [comment]
Thanks, I will reach out. I am trying to get ahold of the private key so I can more easily disperse funds when this arises. I will update here with a link to the transaction once I am able to get the key or arrange for the funds to be sent.

If you could give me an address to send to it would be helpful

**Comment by madbuda** [comment]
I see that you gave me an address already

t1K2XcsKk2gHxT95TLDYauV4SLe8Vps5odu

I just texted the owner of that address, he is sending met he private key when he gets home from work tonight

**Comment by CryptoXman79** [comment]
Ok..waiting thank you.

**Comment by madbuda** [comment]
BTW, I think you meant to say you are going to wait 24 seconds not hours as you already went public with your mistake
https://bitcointalk.org/index.php?topic=2008578.msg27929276#msg27929276

**Comment by CryptoXman79** [comment]
already updated  but understand that when i saw that you had closed my issue, I tought that it was useless to wait...sorry about that.
I will of course post when issue solved !

**Comment by madbuda** [comment]
https://explorer.myhush.org/tx/bea4aa39ea063e4896e3f12688cdd4e40b6da19c830328faf226e0b0aad0a83f

**Comment by SemaRbn** [comment]
Hi. I have the same problem

**Comment by SemaRbn** [comment]
It's hard for me to speak English. I use a translator.
![payout](https://user-images.githubusercontent.com/19171889/34856415-ad4eb76c-f790-11e7-8e68-ccbae03f7223.jpg)
Return to L3gdC6vPKAnRJwXYjcEwTbekoGkptkS7upuUyp7bezAgTj5t2zpx

**Comment by SemaRbn** [comment]
Sorry, t1eftzDw9tsCokY92G79vZcVZDEyfamiyjv

**Comment by madbuda** [comment]
@SemaRbn https://explorer.myhush.org/tx/225fb2cb8cfbdfd9865cef46a58adbee65e3e9101db69c7b9b790f05066661b9

**Comment by SemaRbn** [comment]
Thank you so much :) I thought I lost my coins.

**Comment by madbuda** [comment]
you're not alone, we all got very lucky with this one...

**Comment by CryptoXman79** [comment]
Thank you so much, as you will see, I have post in Bitcointalk ...
Hope this story will help for trapping this bug...
I wish you the best !

**Comment by madbuda** [comment]
@CryptoXman79 appreciate it, it would be nice if you edit you r comments here saying it is a hack and we are stealing.. https://bitcointalk.org/index.php?topic=2008578.msg27924551#msg27924551    

Just click on edit and remove the slander please

**Comment by CryptoXman79** [comment]
Done!
